languageCode = "en"
languageName = "English"
weight = 1
title = "Guilherme Kenzo"
contentDir = 'content/en'

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  # logo = "img/logo.png"
  description = "Guilherme Kenzo - my personal website"
  copyright = "Copyright © - Guilherme Kenzo dos Santos 2024"
  dateFormat = "2 January 2006"

[author]
  name = "Guilherme Kenzo"
  image = "img/profile_photo.png"
  headline = "Law & Technology Researcher, programmer, <br/>tech enthusiast and ex-CTO @ <a href=\"https://turivius.com\">turivius.com</a>"
  bio = "Law & Technology Researcher, programmer, <br/>tech enthusiast and ex-CTO @ <a href=\"https://turivius.com\">turivius.com</a>"
   links = [
     { link = "https://guilhermekenzo.me" },
     { github = "https://github.com/guilherme-kenzo" },
     { email = "mailto:guilherme[at]guilhermekenzo.me" }
   ]
